name: pdfjs
version: 1.10.90

description: Dart bindings for Mozilla's PDF.js library

homepage: https://github.com/Workiva/pdfjs_dart

authors:
  - Sean Burke <sean.burke@workiva.com>

environment:
  sdk: ">=1.24.0 <2.0.0"
